// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx-Bk8U_a-_HZAw-0t3RnophFfVkL6qho',
    appId: '1:219578876393:web:2c648e51b2c9f89a3bcb78',
    messagingSenderId: '219578876393',
    projectId: 'device-streaming-74c1af8e',
    authDomain: 'device-streaming-74c1af8e.firebaseapp.com',
    databaseURL:
        'https://device-streaming-74c1af8e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'device-streaming-74c1af8e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqeTaZ2SMMhzPc0KMuS459P0xdT9ZtyLY',
    appId: '1:219578876393:android:30e897e33871f8ec3bcb78',
    messagingSenderId: '219578876393',
    projectId: 'device-streaming-74c1af8e',
    databaseURL:
        'https://device-streaming-74c1af8e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'device-streaming-74c1af8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOaxWw1BGg1DOzb5A46ivyYqjYqMkGLsA',
    appId: '1:219578876393:ios:03dedf8dd0f7af9f3bcb78',
    messagingSenderId: '219578876393',
    projectId: 'device-streaming-74c1af8e',
    databaseURL:
        'https://device-streaming-74c1af8e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'device-streaming-74c1af8e.firebasestorage.app',
    iosBundleId: 'qmodo.ru.kopim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOaxWw1BGg1DOzb5A46ivyYqjYqMkGLsA',
    appId: '1:219578876393:ios:03dedf8dd0f7af9f3bcb78',
    messagingSenderId: '219578876393',
    projectId: 'device-streaming-74c1af8e',
    databaseURL:
        'https://device-streaming-74c1af8e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'device-streaming-74c1af8e.firebasestorage.app',
    iosBundleId: 'qmodo.ru.kopim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx-Bk8U_a-_HZAw-0t3RnophFfVkL6qho',
    appId: '1:219578876393:web:2c648e51b2c9f89a3bcb78',
    messagingSenderId: '219578876393',
    projectId: 'device-streaming-74c1af8e',
    authDomain: 'device-streaming-74c1af8e.firebaseapp.com',
    databaseURL:
        'https://device-streaming-74c1af8e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'device-streaming-74c1af8e.firebasestorage.app',
  );
}
