// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT3VtuZQqe4NQpcCYA6t5xdDJeGRuVB5M',
    appId: '1:228213546937:web:d0dd6142a848fa1ced2068',
    messagingSenderId: '228213546937',
    projectId: 'kopim-prod',
    authDomain: 'kopim-prod.firebaseapp.com',
    storageBucket: 'kopim-prod.firebasestorage.app',
    measurementId: 'G-6B3VSW4RB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0ngj9jHeheHr_y6lqtO5BX7PHpxQ72MU',
    appId: '1:228213546937:android:9b3a8e5f83ca29d7ed2068',
    messagingSenderId: '228213546937',
    projectId: 'kopim-prod',
    storageBucket: 'kopim-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC32nNc86fHV-tDsZc0qCI4nJpcd-_t3g',
    appId: '1:228213546937:ios:b727392ddecd40cded2068',
    messagingSenderId: '228213546937',
    projectId: 'kopim-prod',
    storageBucket: 'kopim-prod.firebasestorage.app',
    iosBundleId: 'qmodo.ru.kopim',
  );
}
